
import React, { useState } from "react";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { DonutChart } from "@/components/DonutChart";
import { formatCurrency } from "@/components/dashboard/DashboardUtils";
import { Technician } from "@/types/technician";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

interface TechnicianCircleChartsProps {
  filteredTechnicians: Technician[];
}

const TechnicianCircleCharts: React.FC<TechnicianCircleChartsProps> = ({ 
  filteredTechnicians 
}) => {
  const [definitionSearchQuery, setDefinitionSearchQuery] = useState("");
  
  // Calculate total revenue from technicians
  const totalRevenue = filteredTechnicians.reduce((sum, tech) => sum + tech.totalRevenue, 0);
  
  // Calculate total technician payments
  const technicianEarnings = filteredTechnicians.reduce((sum, tech) => 
    sum + tech.totalRevenue * (tech.paymentType === "percentage" ? tech.paymentRate / 100 : 1), 0
  );
  
  // Estimate expenses as 33% of revenue
  const totalExpenses = totalRevenue * 0.33;
  
  // Calculate net profit
  const companyProfit = totalRevenue - technicianEarnings - totalExpenses;
  const companyProfitPercentage = ((companyProfit / totalRevenue) * 100).toFixed(1);
  
  // Revenue breakdown data
  const revenueBreakdown = [
    { name: "Service Revenue", value: totalRevenue * 0.75, color: "#0ea5e9" }, // sky blue
    { name: "Parts & Materials", value: totalRevenue * 0.20, color: "#ec4899" }, // pink
    { name: "Diagnostic Fees", value: totalRevenue * 0.05, color: "#6366f1" },  // indigo
  ];

  // Technician earnings breakdown
  const technicianExpenseBreakdown = [
    { name: "Technician Payments", value: technicianEarnings, color: "#22c55e" },    // green
    { name: "Operating Expenses", value: totalExpenses, color: "#f87171" },    // red
    { name: "Company Profit", value: companyProfit, color: "#3b82f6" },       // blue
  ];

  // Net profit breakdown data
  const profitBreakdown = [
    { name: "Operating Costs", value: companyProfit * 0.3, color: "#3b82f6" }, // blue
    { name: "Reinvestment", value: companyProfit * 0.25, color: "#10b981" },   // green
    { name: "Owner Dividends", value: companyProfit * 0.30, color: "#f59e0b" }, // amber
    { name: "Taxes", value: companyProfit * 0.15, color: "#ef4444" },          // red
  ];
  
  // Financial definitions
  const financialDefinitions = [
    { term: "Gross Revenue", definition: "Total income generated by technician services before any deductions." },
    { term: "Technician Earnings", definition: "Amount paid to technicians based on their payment structure (percentage or flat rate)." },
    { term: "Company Expenses", definition: "Operational costs like equipment, travel, and overhead (estimated at 33% of revenue)." },
    { term: "Net Company Profit", definition: "Revenue remaining after technician payments and company expenses." },
    { term: "Profit Margin", definition: "The percentage of revenue that becomes profit after all expenses." }
  ];
  
  // Filter definitions based on search query
  const filteredDefinitions = financialDefinitions.filter(def => 
    definitionSearchQuery === "" || 
    def.term.toLowerCase().includes(definitionSearchQuery.toLowerCase()) ||
    def.definition.toLowerCase().includes(definitionSearchQuery.toLowerCase())
  );
  
  return (
    <div className="space-y-6">
      {/* Financial Definitions Card */}
      <Card>
        <CardHeader className="pb-2">
          <CardTitle>Financial Definitions</CardTitle>
          <CardDescription>Key financial terms and calculations</CardDescription>
          <div className="mt-2">
            <Input
              placeholder="Search financial definitions..."
              value={definitionSearchQuery}
              onChange={(e) => setDefinitionSearchQuery(e.target.value)}
              className="text-sm"
            />
          </div>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Term</TableHead>
                <TableHead>Definition</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filteredDefinitions.map((def, index) => (
                <TableRow key={index}>
                  <TableCell className="font-medium">{def.term}</TableCell>
                  <TableCell>{def.definition}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
      
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Revenue Breakdown Card */}
        <Card>
          <CardHeader className="pb-2">
            <CardTitle>Revenue Breakdown</CardTitle>
            <CardDescription>Source of revenue streams</CardDescription>
          </CardHeader>
          <CardContent>
            <DonutChart
              data={revenueBreakdown}
              title={formatCurrency(totalRevenue)}
              subtitle="Total Income"
            />
          </CardContent>
        </Card>

        {/* Expense Distribution Card */}
        <Card>
          <CardHeader className="pb-2">
            <CardTitle>Income Distribution</CardTitle>
            <CardDescription>Distribution of earnings between technicians and company</CardDescription>
          </CardHeader>
          <CardContent>
            <DonutChart
              data={technicianExpenseBreakdown}
              title={`${companyProfitPercentage}%`}
              subtitle="Company Profit Margin"
            />
          </CardContent>
        </Card>

        {/* Net Profit Breakdown Card */}
        <Card>
          <CardHeader className="pb-2">
            <CardTitle>Net Company Profit</CardTitle>
            <CardDescription>How profit is distributed</CardDescription>
          </CardHeader>
          <CardContent>
            <DonutChart
              data={profitBreakdown}
              title={formatCurrency(companyProfit)}
              subtitle="Net Company Profit"
            />
          </CardContent>
        </Card>
      </div>
      
      {/* Technician Performance Card - Moved to the bottom as requested */}
      <Card>
        <CardHeader>
          <CardTitle>Technician Financial Performance</CardTitle>
          <CardDescription>Earnings and profit metrics for each technician</CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Technician</TableHead>
                <TableHead>Total Revenue</TableHead>
                <TableHead>Technician Earnings</TableHead>
                <TableHead>Company Earnings</TableHead>
                <TableHead>Profit Ratio</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filteredTechnicians.map((tech) => {
                const techEarnings = tech.totalRevenue * (tech.paymentType === "percentage" ? tech.paymentRate / 100 : 1);
                const companyEarnings = tech.totalRevenue - techEarnings - (tech.totalRevenue * 0.33);
                const profitRatio = ((companyEarnings / tech.totalRevenue) * 100).toFixed(1);
                
                return (
                  <TableRow key={tech.id}>
                    <TableCell className="font-medium">
                      <div className="flex items-center">
                        <div className="w-8 h-8 rounded-full bg-blue-100 flex items-center justify-center text-blue-700 mr-2 text-xs">
                          {tech.initials}
                        </div>
                        <span>{tech.name}</span>
                      </div>
                    </TableCell>
                    <TableCell>{formatCurrency(tech.totalRevenue)}</TableCell>
                    <TableCell>{formatCurrency(techEarnings)}</TableCell>
                    <TableCell>{formatCurrency(companyEarnings)}</TableCell>
                    <TableCell>{profitRatio}%</TableCell>
                  </TableRow>
                );
              })}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
};

export default TechnicianCircleCharts;
