
export type SortOption = 
  | "newest" 
  | "oldest" 
  | "name-asc" 
  | "name-desc" 
  | "revenue-high" 
  | "revenue-low" 
  | "jobs-high" 
  | "jobs-low"
  | "date-asc"
  | "date-desc"
  | "amount-asc"
  | "amount-desc"
  | "status-asc"
  | "status-desc"
  | "profit-high"
  | "profit-low"
  | "amount-high"
  | "amount-low"
  | "rating-high"
  | "rating-low";
