
export interface Technician {
  id: string;
  name: string;
  email: string;
  phone?: string;
  address?: string;
  position?: string;
  department?: string;
  hireDate: string;
  startDate?: string;
  hourlyRate: number;
  paymentRate: number;
  status: string;
  specialty: string;
  skills?: string[];
  location?: string;
  availableDays?: string[];
  workHours?: { start: string; end: string };
  profileImage?: string;
  salary?: number;
  salaryBasis?: 'hourly' | 'weekly' | 'biweekly' | 'monthly' | 'annually' | 'yearly';
  incentiveType?: string;
  incentiveAmount?: number;
  paymentType?: 'percentage' | 'flat' | 'hourly' | 'salary';
  role?: 'technician' | 'contractor' | 'employed' | 'salesman';
  subRole?: string;
  category?: string;
  rating: number;
  completedJobs: number;
  cancelledJobs: number;
  totalRevenue: number;
  initials?: string;
  imageUrl?: string;
  yearsExperience?: number;
  endDate?: string;
  availability?: string[];
  earnings?: number;
  jobCount?: number;
  technicianId?: string;
  date?: string;
  workContract?: string;
  payRate?: number;
  documents?: any[];
  notes?: string;
  ssn?: string;
  idNumber?: string;
  driverLicense?: any;
  certifications?: string[];
  jobCategories?: string[];
}
